name: shelf_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  http: ^0.13.3
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
